export const REGISTRATION_START = "REGISTRATION_START";
export const REGISTRATION_COMPLETE = "REGISTRATION_COMPLETE";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";
export const LOGIN_START = "LOGIN_START";
export const LOGIN_COMPLETE = "LOGIN_COMPLETE";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const STORE_USER_DATA = "STORE_USER_DATA";
export const LOGOUT = "LOGOUT";
