export const SENT_REQUEST = "SENT_REQUEST";
export const DELETE_SENT_REQUEST = "DELETE_SENT_REQUEST";
export const DELETE_RECEIVED_REQUEST = "DELETE_RECEIVED_REQUEST";
export const ACCEPT_REQUEST = "ACCEPT_REQUEST";
