export const SENT_REQUEST = "SENT_REQUEST";
export const DELETE_SENT_REQUEST = "DELETE_SENT_REQUEST";
export const DELETE_RECEIVED_REQUEST = "DELETE_RECEIVED_REQUEST";
export const ACCEPT_REQUEST = "ACCEPT_REQUEST";
export const GET_SENT_REQUESTS = "GET_SENT_REQUESTS";
export const GET_RECEIVE_REQUESTS = "GET_RECEIVE_REQUESTS";
export const GET_FRIENDS_LIST = "GET_FRIENDS_LIST";
